// Generated by Selenium IDE
package edu.pitt.cs;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import static org.hamcrest.MatcherAssert.assertThat;
public class PittEduTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/Users/xiongying/bin/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().window().setSize(new Dimension(1200, 800));
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1TITLE() {
    driver.get("https://www.pitt.edu/");
    assertThat(driver.getTitle(), is("Home | University of Pittsburgh"));
  }
  @Test
  public void tEST2LOGOEXISTS() {
    driver.get("https://www.pitt.edu/");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'University of Pittsburgh\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST3LOGOIMAGE() {
    driver.get("https://www.pitt.edu/");
    {
      WebElement element = driver.findElement(By.xpath("//img[@alt=\"University of Pittsburgh\"]"));
      String attribute = element.getAttribute("src");
      vars.put("logo_src", attribute);
    }
    System.out.println(vars.get("logo_src").toString());
    System.out.println("logo_src");
    assertEquals(vars.get("logo_src").toString(), "https://www.pitt.edu/sites/default/files/assets/pitt_shield_white-home.png");
  }
  @Test
//  ???
  public void tEST4SHCOOLSSCI() {
    driver.get("https://www.pitt.edu/");
    driver.findElement(By.cssSelector(".nav_content_trigger")).click();
    // 4 | waitForElementVisible | id=block-pitt-25-edu-collegesschools-2 | 30000
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-pitt-25-edu-collegesschools-2")));
    assertThat(driver.findElement(By.xpath("//ul[@data-block=\"drawer_nav_right_column\"]/li[3]")).getText(), is("Computing & Information"));
  }
  @Test
  public void tEST5SCHOOLSCOUNT() {
    driver.get("https://www.pitt.edu/");
    driver.findElement(By.cssSelector(".nav_content_trigger")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//ul[@data-block=\"drawer_nav_right_column\"]/li[16]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//ul[@data-block=\"drawer_nav_right_column\"]/li[17]"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void tEST6SEARCHCSC() {
    driver.get("https://www.pitt.edu/");
    driver.findElement(By.cssSelector(".navbar-search")).click();
    // 4 | waitForElementEditable | id=edit-keys | 30000
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.elementToBeClickable(By.id("edit-keys")));
    driver.findElement(By.id("edit-keys")).click();
    driver.findElement(By.id("edit-keys")).sendKeys("computer science club");
    driver.findElement(By.cssSelector(".button")).click();
    // 8 | waitForElementVisible | xpath=//div[10]/div/div/div/a | 30000
    wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[10]/div/div/div/a")));
    List<WebElement> elements = driver.findElements(By.xpath("//a[contains(., \"Student Organization Spotlight\") and contains(., \"Computer Science Club\") and contains(., \"CSC\")]"));
    assert(elements.size() > 0);
  }
}
